[tool.poetry]
name = "demeteor"
version = "0.1.0"
description = "A collection of utility functions for all-sky and spectral meteor cameras"
authors = ["Martin Odokienko <martin.balaz@fmph.uniba.sk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "*"
scipy = "*"
pyyaml = "*"
dotmap = "*"
pandas = "*"
astropy = "*"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
